### ISSUE TITLE
Only populates servicesInfos when file is named .yml not .yaml

### ISSUE THREAD

**Issue by matthewrj** [avast/docker-compose-gradle-plugin#21]
servicesInfos only looks for docker-compose.yml, if the file is named docker-compose.yaml (which mine was), servicesInfos is empty.

**Comment by augi** [comment]
Yes, it's by definition. The default file name is `docker-compose.yml` (see [docs](https://docs.docker.com/compose/compose-file/)). If you want to use different file names then please use `dockerCompose.useComposeFiles` to specify your file names (as shown in README).
