### ISSUE TITLE
Service host is not available for container with HOST networking

### ISSUE THREAD

**Issue by alenkacz** [avast/docker-compose-gradle-plugin#24]
For docker container with HOST networking, this is how docker inspect looks like

```
"Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "52ca975025b511bfc42caf02c4777bdb9ac2570c95c429339364d80d388a2eea",
                    "EndpointID": "0c56d7ee3d9df21d762b0c99ef79b1252476e0cd2cf62a1af0ea588829f1a87e",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
```

Current implementation parses the networks and uses empty string from gateway as hostname. However I think that in that case it should use localhost instead.

**Comment by augi** [comment]
And what's the value of `NetworkSettings.Gateway` (the `Gateway` is on the same level as `Networks`) ? If it's present and it's `localhost` then I would prefer that value because it would handle case of _remove_ Docker daemon.

**Comment by alenkacz** [comment]
NetworkSettings.Gateway is also empty string
