### ISSUE TITLE
Adding function to do pull

### ISSUE THREAD

**Issue by bkrahmer** [avast/docker-compose-gradle-plugin#30]
Hey, thanks for the nice plugin.  I'd like to see docker-compose pull functionality and would be happy to implement it and do a PR, just wanted your feedback to see if you agreed with the idea.  It would be another task you could just add to your build lifecycle.  The ComposeExtension class is holding quite a bit of data.  Do you think it would make sense to have this as a separate task instead?  Doing an analog function of 'build' at the same would probably also make sense.

thanks,
brian

**Comment by augi** [comment]
Hi Brian, thank you for your willingness to contribute!

What do you please mean by the pull functionality? I personally don't use the `pull` command as the images are automatically pulled when used.

**Comment by bkrahmer** [comment]
Yeah, they are pulled the first time if they aren't available locally, but I saw a case where after we updated an image in our docker registry that we didn't see the updated image unless we did a pull.  However, I saw the opposite behavior during a demo this afternoon, so I suspect a cache TTL is involved.  But unless there is another workaround, adding a flag or a task to pull makes sense to me.

cheers,
brian

**Comment by augi** [comment]
We never change tagged images and never use `latest` tag - this is the reason why we've never had this kind of issue.
Could you please explore how the TTL behaves?

Anyway, adding a flag to the Gradle task is IMHO the best way how to implement it. Feel free to prepare a PR, thanks!
