### ISSUE TITLE
Be able to test against multiple docker versions

### ISSUE THREAD

**Issue by alenkacz** [avast/docker-compose-gradle-plugin#32]
Since more functionality is added with newer versions and the old implementation is sometimes changed, I think it might be handy to be able to test the plugin on multiple docker versions...

**Comment by alenkacz** [comment]
@augi any idea how to do this easily?

**Comment by augi** [comment]
It should be possible using [Matrix Build](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix).
