### ISSUE TITLE
Capture container log output

### ISSUE THREAD

**Issue by matthewrj** [avast/docker-compose-gradle-plugin#34]
Is it possible to capture the logs from the containers?

I often want to inspect to logs of a service and right now to achieve that I need to quickly run 
```
docker logs -f <service name>
```
in another terminal while the tests are running. Otherwise I can set removeContainers to false but then I want a fresh container each time I run the test.

**Comment by augi** [comment]
It should be possible. Where do you want to prefer to print the logs to? Should it be disabled by default?

Feel free to prepare PR.
