### ISSUE TITLE
servicesInfos is empty

### ISSUE THREAD

**Issue by alexsapran** [avast/docker-compose-gradle-plugin#35]
Hi all,

I saw on other issues about the support for docker-compose v2 and that the serviceInfos is empty when there is `yaml` instead of `yml` docker-compose file but i think my case is different.

My docker-compose.yml is this
```
version: '2'
services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - "6379:6379"
volumes:
  redis-data:
    driver: local
```
Also tried with version 1 
```
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
```

My project is a multiproject with structure 
```
.
├── admin-panel
│   ├── build
│   └── src
├── api
│   ├── build
│   └── src
├── build
│   └── classes
├── core
│   ├── build
│   ├── lib
│   └── src
├── domain
│   ├── build
│   └── src
```

My gragle build is this
```
dockerCompose.isRequiredBy(test)
    dockerCompose {
        //useComposeFiles = ['../docker-compose.yml'] // like 'docker-compose -f <file>'
        stopContainers = true                                              // useful for debugging
        removeContainers = true
        // removeImages = "None" // Other accepted values are: "All" and "Local"
        // removeVolumes = false
        //environment.put 'BACKEND_ADDRESS', '192.168.1.100' // Pass environment variable to 'docker-compose' for substitution in compose file
        environment local_environment
    }
...
test.doFirst {
        // exposes "${serviceName}_HOST" and "${serviceName}_TCP_${exposedPort}" environment variables
        // for example exposes "WEB_HOST" and "WEB_TCP_80" environment variables for service named `web` with exposed port `80`
        dockerCompose.exposeAsEnvironment(test)
        // exposes "${serviceName}.host" and "${serviceName}.tcp.${exposedPort}" system properties
        // for example exposes "web.host" and "web.tcp.80" system properties for service named `web` with exposed port `80`
        dockerCompose.exposeAsSystemProperties(test)
        dockerCompose.servicesInfos
        // get information about container of service `web` (declared in docker-compose.yml)
        def redis = dockerCompose.servicesInfos
        // pass host and exposed TCP port 80 as custom-named Java System properties
        println "REDIS-------------------"
        println redis;
        systemProperty 'docker.redisIP', redis.getHost()
        //systemProperty 'myweb.port', webInfo.ports[80]
    }
```

And when i run the tests like that
`./gradlew test --tests com..... -p api`
I am getting this output
```
:domain:compileJava UP-TO-DATE
:domain:processResources UP-TO-DATE
:domain:classes UP-TO-DATE
:domain:jar UP-TO-DATE
....
REDIS-------------------
{}
```
Also to point out that the line `redis.getHost()` i have tried with `redis.host` and got the same errors and `def redis = dockerCompose.servicesInfos.redis`

If you need further details let me know.

Regards
Alex.

**Comment by augi** [comment]
Hi,

where do you have the `docker-compose.yml` and the `build.gradle` script you've pasted here? It should be in the same directory. It's strange that your `redis` property is `{}` :(

Also please try to execute the build script with `--info` to get more information about what's happening there.

Btw. if you want to call `getHost()` the you must call it on `dockerCompose.servicesInfos.redis` (not `dockerCompose.servicesInfos`).

**Comment by alexsapran** [comment]
Hi @augi ,

The docker-compose.yml is on the root of the project.
Now if i put the flag i got this in the output 
```
....
Executing task ':domain:composeUp' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'docker-compose''. Working directory: c:\xxxxxx\domain Command: docker-compose build
Successfully started process 'command 'docker-compose''
redis uses an image, skipping
Starting process 'command 'docker-compose''. Working directory: C:\xxxxx\domain Command: docker-compose up -d
Successfully started process 'command 'docker-compose''
cookiesbackend_redis_1 is up-to-date
:domain:composeUp (Thread[main,5,main]) completed. Took 2.889 secs.
:domain:compileTestJava (Thread[main,5,main]) started.
:domain:compileTestJava
...
```
The command of docker-compose up is in an invalid directory, (one path inside my project, the domain folder) now if i set the docker-compose.yml file then i get this error
```
.....
Starting process 'command 'docker-compose''. Working directory: C:\xxxxxx\api Command: docker-compose -f ../docker-compose.yml build
Successfully started process 'command 'docker-compose''
redis uses an image, skipping
Starting process 'command 'docker-compose''. Working directory: C:\xxxxx\api Command: docker-compose -f ../docker-compose.yml up -d
Successfully started process 'command 'docker-compose''
Creating network "cookiesbackend_default" with the default driver
Creating volume "cookiesbackend_redis-data" with local driver
Creating cookiesbackend_redis_1
Starting process 'command 'docker-compose''. Working directory: C:\xxxxx\api Command: docker-compose -f ../docker-compose.yml ps -q redis
Successfully started process 'command 'docker-compose''
Container ID of service redis is 8b8565a69926b661581cddbea712cc70a07996fdceb65c47a46c8d68bb5f3638
Starting process 'command 'docker''. Working directory: C:\xxxx\api Command: docker inspect 8b8565a69926b661581cddbea712cc70a07996fdceb65c47a46c8d68bb5f3638
Successfully started process 'command 'docker''
....
```

Hope that helps.

**Comment by augi** [comment]
Hi,

your scenario is very common and we use it in many project so maybe you use the plugin in wrong way.

If you have the `docker-compose.yml` in the root project then you should apply the plugin on the root project **only**.

Then, if you want to work with the plugin in some of child project (let's say `domain`) than you should just reference the data using `rootProject.dockerCompose` (instead of plain `dockerCompose`).

Hope it helps...

**Comment by alexsapran** [comment]
Thanks for the feedback but i fear i have more questions.

1) When you say apply the plugin on the root project only what do you mean i think i do not fully understand sorry.

2) Also then i run on a module (domain) how do i reference it?

3) Another question if i issue `gradle build` then the plugin will issue docker-compose up for each submodule and when the first's submodules test finish for that submodule it will call the docker-compose stop (cause on the config i have the stop flag) is this expected 

Thanks for your help.

**Comment by augi** [comment]
1. The code `apply plugin: 'docker-compose'` should be on the root project only.
2. If you want to reference `dockerCompose` extension (defined in the root project) then you can use `rootProject.dockerCompose` in the sub-project.
3.  It looks like you have the `docker-compose` plugin applied on all sub-projects and so the plugin is executed multiple times.

It would be great if you can share your project on GitHub so I could make a PR that would fix your issues.  You don't have to share whole project, just leave the stuff that demonstrates issues with the plugin.

Thanks!
