### ISSUE TITLE
Pull task

### ISSUE THREAD

**Issue by antony** [avast/docker-compose-gradle-plugin#40]
By far the most reliable docker plugin I've found. Great work!

I'm noticing the lack of a dockerComposePull task.

Is this something you would consider as a PR? I don't see any other way to ensure I'm using the latest docker images.

**Comment by augi** [comment]
I'll happily accept the PR but I would prefer not to wire the task to other tasks by default because the pull takes usually few seconds.

Btw. I always depend on specific version of image (never depend on `latest`) - it ensures the build is stable even if someone publishes new `latest` image tag. This is the reason why I have never had to implement support for pull.

**Comment by antony** [comment]
That makes sense, but I'm using the plugin for automation tests, so hard-coding to a stable version would somewhat defeat the purpose - we always want to use our latest-release.

I will add the functionality, but of course won't wire it to anything else. Just saves me having a manual exec task in my own gradle scripts.

**Comment by augi** [comment]
> That makes sense, but I'm using the plugin for automation tests, so hard-coding to a stable version would somewhat defeat the purpose - we always want to use our latest-release.

The latest release of your SW surely has some version (like 1.2.3) so I would personally prefer to pass the exact version to your tests somehow (depends on your CI/CD pipeline). You can for example take advantage of [variables in Docker Compose file](https://docs.docker.com/compose/compose-file/#/variable-substitution)

It allows you to test whenever version you want.

**Comment by antony** [comment]
The one thing we are considering doing is dynamically passing a branch name if one exists, since these are automation tests for our web clients, and we might need a specific branch (matching branch name) of the api.

But in a lot of cases we just want to test against :latest, meaning that it would be tested against whatever the current state of the api build's master branch produces.

We only tag if we are releasing to production, and that "stable" build would be considered old, when compared to the current master.

So actually, we have a number of tags `latest-release`, `next-release` etc that get re-tagged a lot. It's no problem for CI because it goes from fresh each time, but locally you can end up with an old image without realising it.
