### ISSUE TITLE
Alternative way for health check

### ISSUE THREAD

**Issue by tadaskay** [avast/docker-compose-gradle-plugin#42]
I'm not able to use docker 1.12 in production as it is not yet available on AWS Elasticbeanstalk. I'm thinking about adding an alternate way to determine container's healthy state. Port checking does not work for me as they become ready immediately, way before actual application startup is completed. Here are some options that could make it work:

- Add an extension option to specify timeout before port probing is even considered. This is simplier, but more error prone as application startup time can very thus often requiring to adjust the timeout manually.
- Add an option to use http based healthcheck (e.g. /health reports 200). Something similar exists in docker-maven-plugin https://github.com/fabric8io/docker-maven-plugin/blob/master/samples/cargo-jolokia-demo/pom.xml#L99.

WDYT?

**Comment by augi** [comment]
I'm aware of the situation that waiting for ports doesn't work on Docker for Windows nor Docker For Mac (ports are available immediately).

I'm now looking for a way how to access the containers directly where ports are open correctly.

Regarding to the http healthchecks - the plugin already has support for Dockerfile [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#/healthcheck) directive so if you have an application then you can use it and it will work :)

**Comment by tadaskay** [comment]
@augi Thanks for the fast response. Like I said, I am not able to use docker 1.12, so HEALTHCHECK (which works just fine) is unfortunately not an option to me.

**Comment by dmitrygusev** [comment]
We do our custom waits in the `doFirst` closure of tasks that depend on `composeUp`, i.e.:

```groovy
    taskThatNeedsDB.dependsOn properties.composeUp
    taskThatNeedsDB.doFirst {
        waitForCreateDB()
    }

    def waitForCreateDB() {
        println "Checking if ${getUrl()} is accessible..."
        def startTime = System.currentTimeMillis()
        def maxWaitMillis = TimeUnit.SECONDS.toMillis(30)
        while (System.currentTimeMillis() - startTime < maxWaitMillis) {
            try {
                def sql = Sql.newInstance(getUrl(), getUsername(), getPassword(), driverClass)
                sql.close()
                println "Connection succeeded!"
                break
            } catch (Exception e) {
                println "Waiting for createdb... (${e.getMessage()})"
                sleep(500)
            }
        }
    }
```

That's for Docker 1.12 for the official Postgres image that doesn't have `HEALTHCHECK` instruction.

**Comment by tadaskay** [comment]
@dmitrygusev Haven't thought of doing that directly in gradle. Thanks a million!

**Comment by augi** [comment]
@tadaskay I haven't encountered any problem with the HEALTHCHECK directive so this is a new information for me :(

I'm not against adding the HTTP checks. How should the API look like?

**Comment by augi** [comment]
I looked into how networking in Docker for Mac/Windows works and the plugin now supports waiting for TCP ports correctly. Checkout out the version `0.3.11` of the plugin.

**Comment by tadaskay** [comment]
I've checked out the new version and it seems to work well on both mac and linux now. So this covers my use case and there's no need for HTTP healthcheck. Previously I used an approach similar to that suggested by @dmitrygusev 

```groovy
class Healthcheck {

    static void waitForHealthcheck(String host, int port) {
        long start = System.currentTimeMillis()
        long maxWait = 200_000
        long initialWait = 60_000
        long retryWait = 5_000

        boolean healthy = false

        println("Waiting for application to become healthy... (initial wait = ${initialWait}ms)")
        sleep(initialWait)

        while (System.currentTimeMillis() - start < maxWait && !healthy) {
            println("Waiting for application to become healthy... (retrying in ${retryWait}ms)")
            sleep(retryWait)
            try {
                healthy = new URL("http://${host}:${port}/health").text == 'OK'
            } catch (Exception ignored) {
            }
        }

        if (healthy) {
            println "Healthcheck SUCCESSFUL after ${System.currentTimeMillis() - start}ms"
        } else {
            throw new RuntimeException('Healthcheck FAILED')
        }
    }

}
```
And calling it from:
```groovy
test.doFIrst {
    Healthcheck.waitForHealthcheck(cmsInfo.host as String, cmsInfo.ports[8080] as int)
}
```

If we were to make this HTTP healthcheck in the plugin, something similar could be done. Just need to allow the user to define which service should be used in the healthcheck (in case of multiple services, like `web` and `db`) and healthcheck path. Furthermore, I did the healthcheck based on the return value, but a simple HTTP status `200` should suffice.

**Comment by augi** [comment]
Cool to hear that the new version works well for you! :)

At this stage, I would prefer not to add HTTP healtchecks into the plugin as the current version works well, supports HEALTCHECK directive, and Docker 2.12 will hopefully available everywhere. Do you agree?

**Comment by tadaskay** [comment]
Sounds good
