### ISSUE TITLE
Support overriding parameters from ComposeExtension

### ISSUE THREAD

**Issue by sepe81** [avast/docker-compose-gradle-plugin#47]
Hey guys. It would be nice to fine tune some of the parameters/variables from `ComposeExtension` within the `dockerCompose` block of `build.gradle`.

As stated in the Tips section of `README.md` "All properties in dockerCompose have meaningful default values so you don't have to touch it" but I think there are some scenarios where overriding would enhance the user experience.

If you startup a container that needs some more time (e.g. 20 seconds) then `waitForOpenTcpPorts` will output `"Waiting for TCP socket on ${service.host}:${forwardedPort} of service '${service.name}' (${e.message})"` about 20 times because `waitAfterTcpProbeFailure` is set to just 1 second.

In this case it would be convinient if I could set the `waitAfterTcpProbeFailure` to for instance 5s within `build.gradle`.

Thanks for this great plugin.

**Comment by augi** [comment]
Hi, the `dockerCompose` block in the `build.gradle` is instance of `ComposeExtension` so you can set the properties of `ComposeExtension` inside the `dockerCompose` block in your `build.gradle`.
