### ISSUE TITLE
Support for version 2 compose files

### ISSUE THREAD

**Issue by madmas** [avast/docker-compose-gradle-plugin#5]
Hi,
if I understand the error message of my build output right, the plugin gets confused by a compose file starting with 

> version: '2'

or did I oversee something?

**Comment by Augi** [comment]
You'are right - there is support for Docker 1.9.1 and docker-compose file v1 - I will add support for `version: 2` during next weekend.

**Comment by Augi** [comment]
The plugin now support both old and new Compose files, and also takes advantage of `docker-compose down` command (if available).

**Comment by madmas** [comment]
Awesome! Thanks a lot!
