### ISSUE TITLE
Examples or Samples

### ISSUE THREAD

**Issue by marcellodesales** [avast/docker-compose-gradle-plugin#65]
Do you have any sample using this plugin?

**Comment by augi** [comment]
Some examples can be seen [in tests](https://github.com/avast/docker-compose-gradle-plugin/blob/master/src/test/groovy/com/avast/gradle/dockercompose/DockerComposePluginTest.groovy)

If you want to see a real-world example, [this project](https://github.com/alenkacz/gradle-marathon-deployer) uses the plugin.
