### ISSUE TITLE
Support for --remove-orphans

### ISSUE THREAD

**Issue by alexarana** [avast/docker-compose-gradle-plugin#72]
I would like to add support for the [--remove-orphans](https://docs.docker.com/compose/reference/up/) option to this plugin.

The said option got added to [version 1.7.0](https://github.com/docker/compose/releases/tag/1.7.0) of docker-compose back in April 2016. I have already done the change and am ready to prepare a PR if agreed.

@augi Thanks again for this very cool project.

**Comment by augi** [comment]
Hi, thanks!

If I understand the option correctly, it collects some garbage, so I'm for using this flag.

According to changelog, this option can be used for `up` and `down` so I would prefer to use it for both commands by default.

Feel free to prepare the PR. It would be nice if the option would be specified only if docker-compose version >= 1.7.0 is detected.
