### ISSUE TITLE
Minor error in README

### ISSUE THREAD

**Issue by andrcuns** [avast/docker-compose-gradle-plugin#77]
In README example of getting information on specific container is not entirely correct - `def webInfo = dockerCompose.servicesInfos.web.'web_1'`
One would first need to access containerInfos map and from that get the key web_1 - `def webInfo = dockerCompose.servicesInfos.web.containerInfos.'web_1'`
Another solution to keep this shorthand format would be to use groovy propertyMissing method like so:
```groovy
def propertyMissing(String name) {
    containerInfos[name]
}
```

**Comment by augi** [comment]
Thanks! Will be released as `0.4.1`.
