### ISSUE TITLE
Issue with option --remove-orphans when stopping containers

### ISSUE THREAD

**Issue by alexarana** [avast/docker-compose-gradle-plugin#79]
Issue #72 added support for the `--remove-orphans` option to both ComposeUp and ComposeDown tasks. However, the implementation of the ComposeDown task adds the said option in the buildup of the 'stop' command and not 'down' where the said option is supported.

I have prepared a PR to fix the said issue:
https://github.com/avast/docker-compose-gradle-plugin/pull/78

**Comment by augi** [comment]
Fixed by #78 and released as `0.4.2`.
