### ISSUE TITLE
docker-compose ps does not show the running containers

### ISSUE THREAD

**Issue by ericfrancis** [avast/docker-compose-gradle-plugin#82]
```
$ ./gradlew composeUp
:composeUp
mysql uses an image, skipping
default_mysql_1 is up-to-date
Will use localhost as host of mysql
Probing TCP socket on localhost:32776 of service 'mysql_1'
TCP socket on localhost:32776 of service 'mysql_1' is ready

BUILD SUCCESSFUL

Total time: 6.075 secs
```

```
$ docker-compose ps
Name   Command   State   Ports
------------------------------
```

I would expect to be able to see the default_mysql_1 listed in the ps output

**Comment by augi** [comment]
We use internally the simplifies identifier, it's `mysql_1` for `default_mysql_1`. So you request is about using the fullname if the waiting code, right?

**Comment by ericfrancis** [comment]
I would expect `docker-compose ps` to show the the running config.

**Comment by augi** [comment]
It depends on how your `docker-compose.yml` and `build.gradle` look like - you must execute the `docker-compose` with the same _project name_ as the Gradle plugin use.

If you are not in `default` directory then according to the service name, you should execute `docker-compose -p default ps`.

**Comment by ericfrancis** [comment]
Gotcha! Let me give that a try

**Comment by ericfrancis** [comment]
Working as you described! Thanks for the quick feedback.
