### ISSUE TITLE
Health check jacoco agent in tcpserver mode

### ISSUE THREAD

**Issue by mdomasevicius** [avast/docker-compose-gradle-plugin#88]
I wish to use `jacocoagent` with docker as a `tcpserver`. Problem is that when I expose a port to the agent, the `gradle docker compose  plugin` fails to check health for it. Is there anyway to skip health check for a specific port? The agent server itself works fine, I am able to run `jacoco:dump` ant task.

**Comment by augi** [comment]
Unfortunately, it's to possible to skip healthcheck for specific service :(

What is the output from the plugin, please? The plugin just waits for TCP port opening...

**Comment by mdomasevicius** [comment]
`$ docker ps`:
```
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                    PORTS                                                                     NAMES
2f915374b7e4        gymdiarycore_app      "/bin/sh -c 'exec ..."   38 seconds ago      Up 36 seconds (healthy)   0.0.0.0:2121->2121/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:32773->8080/tcp   myproject_app_1
```

plugin output:

```
Waiting for TCP socket on localhost:2121 of service 'app_1' (TCP connection on localhost:2121 of service 'app_1' was disconnected right after connected)
Waiting for TCP socket on localhost:2121 of service 'app_1' (TCP connection on localhost:2121 of service 'app_1' was disconnected right after connected)
Waiting for TCP socket on localhost:2121 of service 'app_1' (TCP connection on localhost:2121 of service 'app_1' was disconnected right after connected)
Waiting for TCP socket on localhost:2121 of service 'app_1' (TCP connection on localhost:2121 of service 'app_1' was disconnected right after connected)
```

`docker-compose.test.yml:`

```
app:
  ports:
    - 8080
    - '2121:2121' //jacoco:dump task hardcoded with port 2121
```

P.S. Maybe that could be an improvement for jacoco agent actually...

**Comment by mdomasevicius** [comment]
Or I could contribute a PR for `docker-compose-gradle-plugin`.

WDYT?

**Comment by augi** [comment]
IMHO the Docker image you are using should open all exposed port in meaningful time period after container start. Can you confirm if it's true?

**Comment by mdomasevicius** [comment]
It does expose it. Like I mentioned I am able to fetch `jacoco` execution data from it. However I don't know how docker checks the port for health (whi it thinks it is nor health). Here is what the port is exposed to: [TcpServerOutput.java](https://github.com/jacoco/jacoco/blob/master/org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/output/TcpServerOutput.java)

I can rig up a working setup and link you the repository, but not ASAP.

**Comment by mdomasevicius** [comment]
@augi I've put together the setup: [here](https://github.com/mdomasevicius/gradle-docker-compose-issue).

**Comment by mdomasevicius** [comment]
I've learned by going through discussions that I did a poor job of binding the `tcpserver` to a correct interface.
Jacoco java agent in `tcpserver` mode requires correct configuration of `address` param since by default it binds itself to `loopback`.

Apologies for time wasted 🚒.
