### ISSUE TITLE
Feature Request: improve health check

### ISSUE THREAD

**Issue by bastman** [avast/docker-compose-gradle-plugin#89]
It looks like docker-compose supports these health statuses:
- health: starting
- healthy
- unhealthy

I configured healthcheck in compose.yml:
    healthcheck:
      test: ["CMD", "check-health.sh"]
      interval: 10s
      timeout: 5s
      retries: 3

If the container status changes from -> "health: starting" to "unhealthy" it would be great to fail the composeUp Task (including shutting down the stack: composeDown). Otherwise the gradleTask "composeUp" will hang forever and the compose stack will stay alive. 
Currently if running this scenario (with unhealthy containers) on a CI server again and again - may finally kill the (dockerhost) CI server.  

Would be great to have this feature. What do you think?

**Comment by bastman** [comment]
A quick win, would be to have a timeout configured for the composeUp task, e.g.:

compose.healthCheckTimeoutInSeconds = 60

The composeUp task, could than fail if container's do not get healthy within that timeframe ... and starts shutting down the stack (composeDown)

**Comment by bastman** [comment]
I just realised, shutting down the stack on healthCheckTimeout ^^ should be optional. For local development its nice to ssh into an unhealthy container.

compose.healthCheckTimeoutInSeconds = 60
compose.composeDownOnHealthCheckTimeout = false

... and according to another feature request, it would be great to define all these for a specific configuration, e.g.:

compose.integrationTest ={
  composeFiles:["stack-integration-test.yml"]
  healthCheckTimeoutInSeconds = 60
  composeDownOnHealthCheckTimeout = true
}
compose.dev ={
  composeFiles:["stack-dev.yml"]
  healthCheckTimeoutInSeconds = 60
  composeDownOnHealthCheckTimeout = false
}

**Comment by augi** [comment]
1. Regarding to timeouts - there is [waitForTcpPortsTimeout](https://github.com/avast/docker-compose-gradle-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeExtension.groovy#L24) and [waitForHealthyStateTimeout](https://github.com/avast/docker-compose-gradle-plugin/blob/master/src/main/groovy/com/avast/gradle/dockercompose/ComposeExtension.groovy#L24) properties. Both defaults to 15 minutes - that's probably why you think there is no timeout : )
2. Regarding to calling `composeDown` when something goes wrong - it must be ensured by [finalizedBy](https://docs.gradle.org/3.4.1/dsl/org.gradle.api.Task.html#org.gradle.api.Task:finalizedBy) in your Gradle script. Please note that `finalizedBy` is used by `isRequiredBy` method that is part of our extension.

So I hope both issues are already addressed by the plugin.
