### ISSUE TITLE
Save container output to a file?

### ISSUE THREAD

**Issue by psxpaul** [avast/docker-compose-gradle-plugin#90]
First, thank you for the great plugin.

Is there an easy way of saving the container output to a file? I see there is a `captureContainersOutput` option, but that prints the container output to stdout. Since our application can log a lot of things, our gradle build output becomes a fire hose if I turn this on. But frequently, we have tests fail in CI and I would like to see if there were any errors in the application.

I currently have the following code to do this at the end of a build:
```
composeDown.doFirst {
    mkdir "$buildDir/logs/docker"
    project.exec { ExecSpec e ->
        extension.setExecSpecWorkingDirectory(e)
            e.environment = composeDown.extension.environment
            e.commandLine composeDown.extension.composeCommand('logs', '--no-color', 'app')
            e.standardOutput = new FileOutputStream("$buildDir/logs/docker/app.log")
    }
}
```

This is somewhat cumbersome though, and relies on the current implementation of the composeDown task. It also doesn't write the log files until the end of the build. Ideally, the `captureContainersOutput` option could take a file or outputstream to make this easier.

**Comment by augi** [comment]
Hi, it's to possible to save the container output to a file but I like that feature so I would like to implement it soon (or feel free to prepare a PR).

**Comment by antinodes** [comment]
Is there interest in extending this feature to support a separate file per container?  Personally, I find it difficult to read the logs when they are all interleaved.
